### ISSUE TITLE
Clicks from Context Menu in Firefox sends referrer

### ISSUE THREAD

**Issue by 0x46616c6b** [ether/ep_hide_referrer#18]
There is a serious problem in recent Firefox versions. When you use the context menu entry "open in new tab" on a link in a pad the referrer will transferred. 

### Steps to reproduce

- use firefox (in my case version 54 and 55)
- go to the pad https://pad.systemli.org/p/referrer-test
- right click on the link -> open in new tab
- the page shows the referrer

### Idea

Register not only a on click handler and replace every href with the own redirect url.

**Comment by JohnMcLear** [comment]
Sorry I neglected this for so long, I rewrote and included your fixes so thanks :)
