### ISSUE TITLE
DOM based XSS in redirect page

### ISSUE THREAD

**Issue by mrpinghe** [ether/ep_hide_referrer#6]
with a malformed redirect URL, XSS is possible and it bypasses browser's filter as well

example. /redirect#https%3A//www.google.com#%22%3e%3cimg%20src=%22#%22%20onerror=%22alert(%27pwned%27)

**Comment by nashe** [comment]
This issue is still present today (http://localhost:9001/redirect#http://%3Cimg%20src=#%20onerror=alert(document.domain)%3E), this issue should be re-opened. 
I'm starting to write a fix.

**Comment by nashe** [comment]
PR landed.

**Comment by nashe** [comment]
Seems to be related to https://github.com/ether/etherpad-lite/issues/3323.
